[build]
  command = "pnpm install && pnpm run build"
  publish = "dist"

[build.environment]
  NETLIFY_USE_PNPM = "true"
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
