export type FuelCategoryId = "recovery" | "energy" | "focus" | "build" | "quick";

export interface Recipe {
  id: string;
  number: string;
  name: string;
  why: string;
  prepTime: string;
  cookTime: string;
  servings: string;
  ingredients: string[];
  instructions: string[];
  athleteTip: string;
  protein: string;
  carbs: string;
  fat: string;
  pdfUrl?: string;
  videoUrl?: string;
}

export interface FuelCategory {
  id: FuelCategoryId;
  label: string;
  accentColor: string;
  tagline: string;
  overview: {
    paragraphs: string[];
    when: string;
    lookFor: string[];
    avoid: string[];
    lawTieIn: string;
  };
  recipes: Recipe[];
}

function r(
  categoryId: FuelCategoryId,
  index: number,
  data: Omit<Recipe, "id" | "number">
): Recipe {
  return { id: `${categoryId}-${index}`, number: String(index).padStart(2, "0"), ...data };
}

export const FUEL_CATEGORIES: FuelCategory[] = [
  {
    id: "recovery",
    label: "Recovery Fuel",
    accentColor: "#00D4C8",
    tagline: "What you eat after you work to rebuild faster.",
    overview: {
      paragraphs: [
        "After you train, your body is in repair mode. What you eat in the first 30–45 minutes after practice determines how fast you recover, how sore you are tomorrow, and how ready you are for the next session.",
        "Recovery fuel is protein to rebuild muscle and carbohydrates to restore glycogen. It is not optional it is the difference between building and breaking down. Most athletes skip this window and wonder why they are always tired and sore.",
        "The goal is simple: get protein and carbs into your body within 45 minutes of finishing. It doesn't have to be a full meal. A shake, some yogurt with fruit, chocolate milk anything that delivers both. Then eat a full meal within 2 hours.",
      ],
      when: "Within 30–45 minutes after practice or competition. Follow with a full meal within 2 hours.",
      lookFor: [
        "Complete proteins chicken, eggs, dairy, Greek yogurt, cottage cheese",
        "Fast-digesting carbohydrates fruit, white rice, sweet potato",
        "Fluids + electrolytes to rehydrate",
        "Aim for roughly 20–30g protein and 40–60g carbs",
      ],
      avoid: [
        "High-fat foods in the immediate recovery window they slow digestion",
        "Skipping recovery fuel entirely even busy schedules need a 5-minute solution",
        "High-fiber foods right after training they can cause GI distress",
        "Waiting more than 2 hours to eat a real meal",
      ],
      lawTieIn: "Recovery is not rest it is work you do for tomorrow. The athlete who shows up to the next practice recovered is the athlete who builds faster.",
    },
    recipes: [
      r("recovery", 1, {
        name: "Hamburger Pasta",
        why: "One-pan family-style meal with ground beef and pasta delivering the protein and carbohydrate combination ideal for muscle repair and glycogen restoration after practice or competition.",
        prepTime: "10 min", cookTime: "25 min", servings: "6",
        protein: "38g", carbs: "52g", fat: "16g",
        pdfUrl: "hamburger-pasta.pdf",
        ingredients: [
          "1 lb elbow macaroni (dry)",
          "1 lb ground beef",
          "1 tbsp avocado oil",
          "1 cup chopped onions",
          "1 cup shredded lettuce",
          "½ cup chopped pickles",
          "2 tbsp steak seasoning (such as Montreal Steak Seasoning)",
          "8 oz block cheddar cheese, shredded",
          "3 tbsp flour",
          "2 tbsp butter",
          "3 cups milk",
        ],
        instructions: [
          "Cook pasta in salted water until al dente. Drain and set aside.",
          "In a large pan, heat avocado oil. Brown the ground beef with steak seasoning.",
          "In a separate saucepan, melt butter. Whisk in flour to form a roux. Slowly add milk, stirring until smooth. Add shredded cheddar and stir until melted.",
          "Combine pasta, beef mixture, and cheese sauce. Top with onions, lettuce, and pickles. Mix well and serve.",
        ],
        athleteTip: "Best as a post-practice dinner or post-competition recovery meal. Also works the night before a competition eaten 3–4 hours before bed to load glycogen overnight. Avoid within 2–3 hours before competition.",
      }),
      r("recovery", 2, {
        name: "Chicken + Brown Rice Bowl",
        why: "A classic combination lean protein from chicken plus complex carbs from brown rice rebuilds muscle and restores energy.",
        prepTime: "10 min", cookTime: "30 min", servings: "2",
        protein: "45g", carbs: "55g", fat: "8g",
        ingredients: [
          "2 chicken breasts (about 6 oz each)",
          "1 cup brown rice (dry)",
          "2 cups chicken broth or water",
          "1 tbsp olive oil",
          "1 tsp garlic powder",
          "1 tsp onion powder",
          "Salt and pepper to taste",
          "Optional: steamed broccoli, diced bell pepper, or your choice of vegetables",
        ],
        instructions: [
          "Cook brown rice in chicken broth according to package directions, about 25–30 minutes.",
          "Season chicken breasts with garlic powder, onion powder, salt, and pepper.",
          "Heat olive oil in a pan over medium-high heat. Cook chicken 6–7 minutes per side until cooked through (internal temp 165°F).",
          "Rest chicken 5 minutes, then slice or dice.",
          "Serve chicken over rice with vegetables if using.",
        ],
        athleteTip: "Double the recipe and keep portions in containers for 3 days of post-practice meals. Season extra and keep plain so you can pair with different sauces each day.",
      }),
      r("recovery", 3, {
        name: "Greek Yogurt Berry Parfait",
        why: "Greek yogurt delivers 15–20g protein per cup with live cultures that support gut health and recovery. Layers of fruit and granola add fast carbs to restore glycogen.",
        prepTime: "5 min", cookTime: "0 min", servings: "1",
        protein: "20g", carbs: "38g", fat: "5g",
        ingredients: [
          "1½ cups plain Greek yogurt (2%)",
          "1 cup mixed berries (fresh or thawed frozen)",
          "¼ cup granola",
          "1 tbsp honey",
          "Optional: 1 tbsp chia seeds",
        ],
        instructions: [
          "Layer half the Greek yogurt in a bowl or jar.",
          "Add half the berries.",
          "Repeat the layers.",
          "Top with granola and drizzle with honey.",
          "Add chia seeds if using. Eat immediately or refrigerate up to 4 hours.",
        ],
        athleteTip: "Make 3–4 jars at the start of the week. Add granola right before eating to keep it crunchy. Works as an immediate post-practice snack before your full recovery meal.",
      }),
      r("recovery", 4, {
        name: "Turkey & Avocado Wrap",
        why: "A portable recovery option that travels well to tournaments and away games. Turkey delivers lean protein and avocado adds healthy fat that supports hormone recovery.",
        prepTime: "8 min", cookTime: "0 min", servings: "1",
        protein: "32g", carbs: "42g", fat: "14g",
        ingredients: [
          "1 large whole wheat tortilla",
          "4 oz sliced turkey breast (deli or cooked)",
          "½ ripe avocado, sliced",
          "1 cup baby spinach or romaine",
          "2 slices tomato",
          "1 tbsp hummus or Greek yogurt spread",
          "Salt, pepper, and a squeeze of lemon",
        ],
        instructions: [
          "Lay tortilla flat on a clean surface.",
          "Spread hummus or Greek yogurt across the center.",
          "Layer spinach, turkey, avocado, and tomato.",
          "Season with salt, pepper, and a squeeze of lemon.",
          "Fold in the sides and roll tightly. Slice in half.",
        ],
        athleteTip: "Make 5 wraps on Sunday night and grab one after every practice this week. Wrap individually in foil and refrigerate. They hold well for 3 days.",
      }),
      r("recovery", 5, {
        name: "Salmon Sweet Potato Plate",
        why: "Omega-3s in salmon reduce inflammation, making it one of the best recovery proteins available. Sweet potato delivers fast-digesting carbs to restore glycogen.",
        prepTime: "10 min", cookTime: "25 min", servings: "2",
        protein: "36g", carbs: "38g", fat: "12g",
        ingredients: [
          "2 salmon fillets (about 6 oz each)",
          "2 medium sweet potatoes",
          "1 tbsp olive oil",
          "1 tsp garlic powder",
          "1 tsp paprika",
          "Salt and pepper to taste",
          "Optional: lemon wedges and steamed green vegetables",
        ],
        instructions: [
          "Preheat oven to 400°F.",
          "Pierce sweet potatoes with a fork. Microwave 8–10 minutes until soft, or bake alongside salmon.",
          "Rub salmon fillets with olive oil, garlic powder, paprika, salt, and pepper.",
          "Place on a lined baking sheet and bake 12–15 minutes until salmon flakes easily.",
          "Slice sweet potato open and serve alongside salmon. Add lemon and vegetables if using.",
        ],
        athleteTip: "Bake a full sheet of salmon fillets and sweet potatoes at once. 25 minutes and you have 2 days of post-practice meals ready. Keep portions in containers.",
      }),
      r("recovery", 6, {
        name: "Peanut Butter Banana Toast",
        why: "Quick, portable, and delivers protein plus fast-acting carbs without any cooking. Banana provides potassium to replace what's lost in sweat.",
        prepTime: "5 min", cookTime: "2 min", servings: "1",
        protein: "18g", carbs: "48g", fat: "12g",
        ingredients: [
          "2 slices whole grain bread",
          "2 tbsp natural peanut butter",
          "1 medium banana, sliced",
          "1 tsp honey",
          "Optional: sprinkle of chia seeds or hemp seeds",
        ],
        instructions: [
          "Toast bread to your preference.",
          "Spread 1 tbsp peanut butter on each slice.",
          "Layer banana slices on top.",
          "Drizzle with honey.",
          "Add chia or hemp seeds if using. Eat immediately.",
        ],
        athleteTip: "Keep whole grain bread, a jar of PB, and bananas in your kitchen at all times. This is a 5-minute recovery meal with zero prep and zero excuses.",
      }),
      r("recovery", 7, {
        name: "Cottage Cheese Fruit Bowl",
        why: "Cottage cheese is high in casein protein a slow-digesting protein ideal for overnight muscle repair. The fruit adds fast carbs to replenish glycogen immediately post-training.",
        prepTime: "3 min", cookTime: "0 min", servings: "1",
        protein: "24g", carbs: "28g", fat: "5g",
        ingredients: [
          "1½ cups low-fat cottage cheese",
          "1 cup fruit of choice (pineapple chunks, peach slices, or mixed berries)",
          "1 tbsp honey or agave",
          "Optional: sprinkle of cinnamon",
        ],
        instructions: [
          "Scoop cottage cheese into a bowl.",
          "Top with your choice of fruit.",
          "Drizzle with honey.",
          "Add cinnamon if using. Eat immediately or refrigerate up to 24 hours (add fruit fresh when serving).",
        ],
        athleteTip: "The best recovery bowl that requires zero cooking. Keep cottage cheese and fruit stocked and this is always 3 minutes away. Pineapple is especially good as it contains bromelain which supports muscle recovery.",
      }),
      r("recovery", 8, {
        name: "Veggie Egg Scramble",
        why: "Eggs are a complete protein. Pairing with vegetables adds iron, folate, and micronutrients essential for tissue repair after training.",
        prepTime: "5 min", cookTime: "8 min", servings: "1",
        protein: "22g", carbs: "12g", fat: "14g",
        ingredients: [
          "3 large eggs",
          "1 cup baby spinach",
          "½ cup diced bell pepper",
          "¼ cup diced onion",
          "1 tbsp olive oil or butter",
          "Salt, pepper, and garlic powder to taste",
          "Optional: shredded cheese or salsa to top",
        ],
        instructions: [
          "Whisk eggs in a bowl with salt, pepper, and garlic powder.",
          "Heat oil in a non-stick pan over medium heat.",
          "Add bell pepper and onion. Cook 2–3 minutes until softened.",
          "Add spinach and toss until wilted, about 1 minute.",
          "Pour in eggs and stir gently until just set, about 2–3 minutes.",
          "Top with cheese or salsa if using.",
        ],
        athleteTip: "Add a handful of spinach to any egg scramble. You won't taste it and it adds iron and folate critical for recovery. Prep the vegetables on Sunday so this is a 5-minute meal on busy practice nights.",
      }),
      r("recovery", 9, {
        name: "Overnight Recovery Oats",
        why: "Prep the night before so post-practice recovery fuel is ready the second you need it. Oats deliver complex carbs, Greek yogurt adds protein, and chia seeds provide omega-3s.",
        prepTime: "5 min", cookTime: "0 min", servings: "1",
        protein: "22g", carbs: "58g", fat: "8g",
        ingredients: [
          "½ cup rolled oats (not instant)",
          "1 cup milk or unsweetened almond milk",
          "½ cup plain Greek yogurt",
          "1 tbsp chia seeds",
          "1 tbsp honey or maple syrup",
          "½ cup fresh or frozen berries",
          "Optional: 1 scoop vanilla protein powder",
        ],
        instructions: [
          "Combine oats, milk, Greek yogurt, chia seeds, and honey in a jar or container.",
          "Stir well to combine everything.",
          "Add berries on top.",
          "Seal and refrigerate overnight (minimum 4 hours).",
          "Grab from the fridge and eat cold, or warm briefly in the microwave.",
        ],
        athleteTip: "Make 5 jars on Sunday. Breakfast and recovery fuel handled for the whole week. Use rolled oats, not instant. Real oats deliver sustained energy that instant oats don't.",
      }),
      r("recovery", 10, {
        name: "Tuna Quinoa Bowl",
        why: "High protein, complete amino acids, and anti-inflammatory omega-3s in one bowl. Quinoa is the only plant grain that delivers all essential amino acids.",
        prepTime: "10 min", cookTime: "15 min", servings: "2",
        protein: "38g", carbs: "42g", fat: "9g",
        ingredients: [
          "1 cup quinoa (dry)",
          "2 cups water or chicken broth",
          "2 cans (5 oz each) tuna in water, drained",
          "1 cup diced cucumber",
          "½ cup cherry tomatoes, halved",
          "¼ cup diced red onion",
          "2 tbsp olive oil",
          "Juice of 1 lemon",
          "Salt, pepper, and fresh parsley or dill",
        ],
        instructions: [
          "Rinse quinoa and cook in broth or water over medium heat 12–15 minutes until fluffy. Let cool slightly.",
          "Drain tuna and fluff with a fork.",
          "Combine quinoa, tuna, cucumber, tomatoes, and red onion in a bowl.",
          "Drizzle with olive oil and lemon juice.",
          "Season with salt, pepper, and herbs. Mix well and serve.",
        ],
        athleteTip: "Keep canned tuna stocked at all times. It's one of the highest protein-to-cost foods available. Cook a batch of quinoa on Sunday and this bowl is ready in 10 minutes flat any night of the week.",
      }),
      r("recovery", 11, {
        name: "High Octane Yogurt Parfait",
        why: "Greek yogurt delivers fast-absorbing protein and is easier on the stomach than other dairy. Chia seeds add omega-3s, fiber, and minerals that fight muscle cramps. Granola provides complex carbs for sustained energy. Works as a full meal or a pre- or post-workout snack depending on your portion size.",
        prepTime: "10 min", cookTime: "15 min", servings: "3–4",
        protein: "25g", carbs: "48g", fat: "7g",
        videoUrl: "https://youtu.be/v9d7qEeiLsg",
        ingredients: [
          "2 cups plain Greek yogurt",
          "2 cups fresh berries (strawberries, blueberries, raspberries, or blackberries)",
          "¼ cup chia seeds",
          "3 tbsp honey",
          "1–2 tbsp fresh lemon juice (added if pan gets dry while cooking)",
          "½ cup granola",
          "Glass jars for serving and storage",
        ],
        instructions: [
          "Chop berries into bite-sized pieces based on preference.",
          "Heat a cast iron skillet over medium heat. Add the berries.",
          "Stir in chia seeds and honey. Mix well to combine.",
          "Simmer 8–10 minutes, stirring occasionally, until the berries break down into a thick jam. If the pan gets too dry, add a squeeze of lemon juice to loosen.",
          "Transfer the berry jam to jars and cool in the refrigerator for at least 20 minutes.",
          "Build your parfaits: spoon a base layer of Greek yogurt into each jar, add a layer of berry jam, then a second layer of yogurt, and top with granola.",
          "Seal and refrigerate for up to 4 days.",
        ],
        athleteTip: "Pre-workout: eat 1–2 hours before practice or competition. The granola provides complex carbs for sustained court energy. Post-workout: the Greek yogurt reduces inflammation and supports muscle repair. These travel well for tournaments and the mess stays contained in the jar. Variations: mix different berry combinations, stir collagen powder, creatine, or protein powder directly into the yogurt layer, add vanilla extract, or mix in matcha, cacao, or any other performance powder you use.",
      }),
    ],
  },
  {
    id: "energy",
    label: "Energy Fuel",
    accentColor: "#FF2D78",
    tagline: "What you eat before you compete to show up ready.",
    overview: {
      paragraphs: [
        "Pre-competition nutrition is not about eating more it is about eating right and eating at the right time. The goal is stable blood sugar, enough fuel in the tank, and nothing that creates sluggishness or GI issues on the court.",
        "Energy fuel is timed carbohydrates, moderate protein, and low fat and fiber in the hours before competition. Fat and fiber slow digestion the last thing you want before a game is food sitting in your stomach on the court.",
        "Timing matters as much as content. A full meal 3–4 hours before, a lighter snack 60–90 minutes before, and something small (banana, rice cake, sports drink) right before if needed. Experiment in practice never try something new on game day.",
      ],
      when: "Full meal 3–4 hours before. Light snack 60–90 minutes before. Small top-off 15–30 minutes before if needed.",
      lookFor: [
        "Easy-digesting carbohydrates white rice, pasta, bread, banana, oatmeal",
        "Moderate lean protein chicken, turkey, eggs",
        "Familiar foods your body knows game day is not the time to experiment",
        "Consistent hydration starting the night before",
      ],
      avoid: [
        "High-fat foods within 2 hours of competition",
        "High-fiber foods beans, raw vegetables, whole grains too close to game time",
        "New or unfamiliar foods on competition day",
        "Under-fueling showing up to compete with an empty tank is a performance killer",
      ],
      lawTieIn: "You cannot perform beyond what you've prepared for. Fueling the game starts the night before, not 30 minutes before tip-off.",
    },
    recipes: [
      r("energy", 1, {
        name: "Pre-Game Pasta with Marinara",
        why: "The classic pre-game meal. Complex carbs from pasta load glycogen stores without weighing you down. Simple marinara keeps fat low so digestion stays fast.",
        prepTime: "10 min", cookTime: "15 min", servings: "2",
        protein: "22g", carbs: "78g", fat: "5g",
        ingredients: [
          "8 oz pasta (penne, spaghetti, or rigatoni)",
          "1 cup marinara sauce",
          "3 oz lean ground turkey or grilled chicken breast, diced",
          "1 tbsp olive oil",
          "2 cloves garlic, minced",
          "Salt to taste",
          "Optional: fresh basil and parmesan (small amount)",
        ],
        instructions: [
          "Cook pasta in well-salted water until al dente. Drain and set aside.",
          "In a pan, heat olive oil. Add garlic and cook 1 minute.",
          "Add ground turkey or chicken and cook through, about 5–6 minutes.",
          "Add marinara sauce and stir to combine. Simmer 3 minutes.",
          "Toss pasta in the sauce. Top with fresh basil and a small amount of parmesan if using.",
        ],
        athleteTip: "Eat this the night before a morning game, not the morning of. Let it work overnight loading glycogen. Keep the sauce simple and low-fat so digestion stays fast.",
      }),
      r("energy", 2, {
        name: "Banana Almond Butter Toast",
        why: "Fast, portable, and delivers quick carbs plus healthy fat and protein in under 5 minutes. Banana provides potassium and easily digested natural sugar for immediate energy.",
        prepTime: "5 min", cookTime: "2 min", servings: "1",
        protein: "10g", carbs: "45g", fat: "10g",
        ingredients: [
          "2 slices whole grain bread",
          "2 tbsp almond butter",
          "1 medium banana, sliced",
          "½ tsp cinnamon",
          "Optional: drizzle of honey",
        ],
        instructions: [
          "Toast bread to your preference.",
          "Spread almond butter evenly across each slice.",
          "Layer banana slices on top.",
          "Sprinkle with cinnamon.",
          "Drizzle with honey if using. Eat within 30 minutes for best energy timing.",
        ],
        athleteTip: "Keep bananas and almond butter in your bag at all times. This is the best emergency pre-game fuel when nothing else is available. Easy on the stomach and fast to digest.",
      }),
      r("energy", 3, {
        name: "Champion Morning Oatmeal",
        why: "A warm, steady-energy breakfast that keeps blood sugar stable through a long morning game. Oats release energy slowly so there's no spike and crash mid-competition.",
        prepTime: "5 min", cookTime: "5 min", servings: "1",
        protein: "14g", carbs: "62g", fat: "6g",
        ingredients: [
          "1 cup rolled oats",
          "2 cups milk (for more protein and calories than water)",
          "1 medium banana, sliced",
          "1 tbsp honey or maple syrup",
          "1 tsp cinnamon",
          "Optional: handful of blueberries or 1 tbsp nut butter",
        ],
        instructions: [
          "Combine oats and milk in a small saucepan over medium heat.",
          "Cook 4–5 minutes, stirring frequently, until oats are creamy and thick.",
          "Pour into a bowl.",
          "Top with banana slices, honey, and cinnamon.",
          "Add berries or nut butter if using.",
        ],
        athleteTip: "Cook with milk instead of water for more protein and calories without any extra effort. Eat this 2.5–3 hours before game time for steady energy through warmups and early play.",
      }),
      r("energy", 4, {
        name: "Rice Cakes with Honey & PB",
        why: "The simplest pre-game snack. Fast carbs from rice cakes and honey, a little protein and fat from peanut butter, and nothing that upsets your stomach.",
        prepTime: "3 min", cookTime: "0 min", servings: "1",
        protein: "6g", carbs: "38g", fat: "5g",
        ingredients: [
          "3 plain rice cakes",
          "1½ tbsp natural peanut butter",
          "1 tbsp honey",
          "Optional: sliced banana on top",
        ],
        instructions: [
          "Lay rice cakes flat on a plate or flat surface.",
          "Spread peanut butter evenly across each rice cake.",
          "Drizzle honey over each.",
          "Add banana slices if using.",
          "Eat immediately.",
        ],
        athleteTip: "Plain rice cakes with honey and a little PB are the most underrated athlete snack in existence. Keep a bag in your tournament bag permanently. Best eaten 60–90 minutes before game time.",
      }),
      r("energy", 5, {
        name: "Mango Pineapple Smoothie",
        why: "A light, easy-to-digest liquid meal for athletes who get nervous before games and can't eat solid food. Natural fruit sugars provide quick energy without heaviness.",
        prepTime: "5 min", cookTime: "0 min", servings: "1",
        protein: "8g", carbs: "58g", fat: "2g",
        ingredients: [
          "1 cup frozen mango chunks",
          "½ cup frozen pineapple",
          "1 cup coconut water or orange juice",
          "½ cup plain Greek yogurt",
          "Optional: 1 scoop vanilla protein powder",
        ],
        instructions: [
          "Add coconut water or juice to blender first.",
          "Add frozen mango and pineapple.",
          "Add Greek yogurt.",
          "Blend until completely smooth. Add more liquid if too thick.",
          "Drink immediately.",
        ],
        athleteTip: "Freeze mango chunks in pre-portioned bags. Just dump and blend. Great for athletes who struggle to eat before competition. Drink 60–90 minutes before game time.",
      }),
      r("energy", 6, {
        name: "Everything Bagel with Egg",
        why: "A complete pre-game meal with fast-digesting carbs from the bagel and protein from eggs. Ready in 10 minutes and easy on the stomach.",
        prepTime: "5 min", cookTime: "5 min", servings: "1",
        protein: "22g", carbs: "48g", fat: "10g",
        ingredients: [
          "1 plain or everything bagel, toasted",
          "2 large eggs",
          "1 tsp butter or olive oil",
          "1 oz cream cheese or 1 slice cheese",
          "Salt and pepper to taste",
        ],
        instructions: [
          "Toast bagel until golden.",
          "Heat butter in a small pan over medium heat.",
          "Cook eggs to your preference — scrambled or fried.",
          "Season with salt and pepper.",
          "Spread cream cheese on the toasted bagel. Top with eggs.",
        ],
        athleteTip: "Keep hard-boiled eggs in the fridge all week. Game-morning breakfast done in 3 minutes with zero cooking. Eat 2.5–3 hours before competition for best digestion.",
      }),
      r("energy", 7, {
        name: "Baked Sweet Potato with Butter",
        why: "One of the cleanest carb sources available. Easy to digest, satisfying, and versatile. Sweet potato digests more slowly than white rice, making it ideal 3+ hours before game time.",
        prepTime: "5 min", cookTime: "10 min", servings: "1",
        protein: "4g", carbs: "52g", fat: "6g",
        ingredients: [
          "1 large sweet potato",
          "1 tbsp butter",
          "Pinch of salt",
          "Optional: cinnamon and honey, or a small pinch of brown sugar",
        ],
        instructions: [
          "Pierce sweet potato all over with a fork.",
          "Microwave on high 8–10 minutes, turning halfway, until completely soft when pierced.",
          "Or bake at 400°F for 45 minutes for a crispier skin.",
          "Slice open lengthwise.",
          "Add butter, salt, and optional toppings. Serve immediately.",
        ],
        athleteTip: "Batch-cook 5 sweet potatoes on Sunday. Microwave one in 2 minutes flat for a fast pre-game carb source all week. A completely reliable, stomach-friendly fuel source.",
      }),
      r("energy", 8, {
        name: "Whole Grain Waffles with Maple",
        why: "A tournament morning staple. Whole grain waffles deliver steady carbs and the maple syrup adds quick-acting natural sugar for an energy boost close to game time.",
        prepTime: "5 min", cookTime: "5 min", servings: "1",
        protein: "10g", carbs: "62g", fat: "8g",
        ingredients: [
          "2 whole grain waffles (frozen store-bought or homemade)",
          "2 tbsp pure maple syrup",
          "1 cup fresh or thawed berries",
          "Optional: 1 tbsp almond butter or a dollop of Greek yogurt",
        ],
        instructions: [
          "Toast waffles directly from frozen until golden and crispy.",
          "Top with berries.",
          "Drizzle maple syrup evenly over both waffles.",
          "Add almond butter or Greek yogurt on the side if using.",
        ],
        athleteTip: "Freeze individual waffles and toast them directly. No prep, tournament-ready breakfast in 3 minutes. Make a big batch on Sunday and freeze separated by parchment paper.",
      }),
      r("energy", 9, {
        name: "Carb-Loading Grain Bowl",
        why: "Layers of rice, quinoa, and avocado build a high-carb base without fiber overload. This bowl fuels long tournament days where energy needs are high across multiple games.",
        prepTime: "5 min", cookTime: "20 min", servings: "1",
        protein: "18g", carbs: "72g", fat: "10g",
        ingredients: [
          "½ cup cooked white rice",
          "½ cup cooked quinoa",
          "½ ripe avocado, sliced",
          "1 egg (fried or soft-boiled)",
          "1 tbsp soy sauce or tamari",
          "½ tsp sesame oil",
          "Optional: edamame and cucumber slices",
        ],
        instructions: [
          "Cook white rice and quinoa (or use leftovers).",
          "Warm rice and quinoa and add to a bowl.",
          "Fan avocado slices on top.",
          "Add egg cooked to your preference.",
          "Drizzle soy sauce and sesame oil. Add edamame or cucumber if using.",
        ],
        athleteTip: "Use leftover rice and quinoa from the week. Add avocado and a fried egg and you have a game-day bowl in 5 minutes. Eat 3–4 hours before your first game.",
      }),
      r("energy", 10, {
        name: "No-Bake Energy Bites",
        why: "Make a big batch on Sunday and grab 2–3 as a pre-game snack all week. Rolled oats, peanut butter, and honey deliver steady carbs and energy in a portable, no-mess format.",
        prepTime: "15 min", cookTime: "0 min", servings: "6",
        protein: "8g", carbs: "28g", fat: "8g",
        ingredients: [
          "1 cup rolled oats",
          "½ cup natural peanut butter",
          "⅓ cup honey",
          "½ cup mini chocolate chips",
          "¼ cup ground flaxseed",
          "1 tsp vanilla extract",
        ],
        instructions: [
          "Combine all ingredients in a large mixing bowl.",
          "Stir until everything is fully combined and dough-like.",
          "Cover and refrigerate for 30 minutes.",
          "Roll into 1-inch balls using your hands.",
          "Store in an airtight container in the refrigerator. Makes about 12 bites.",
        ],
        athleteTip: "Roll into balls and freeze. They last 2 weeks and travel perfectly to tournaments. Grab 2 as a 60–90 minute pre-game snack. Keep extras in your gym bag zipped in a small container.",
      }),
    ],
  },
  {
    id: "focus",
    label: "Focus Fuel",
    accentColor: "#2B8BF5",
    tagline: "What supports brain function, clarity, and emotional regulation.",
    overview: {
      paragraphs: [
        "Focus is a physical state, not just a mental one. The brain runs on glucose, and when blood sugar drops, focus and emotional regulation drop with it. This is not motivation it is biology.",
        "Focus fuel is steady energy foods that release slowly, support hydration, and reduce inflammation. Omega-3 fatty acids, antioxidants, and stable blood sugar are the three pillars of brain performance. When an athlete is under-fueled or eating in ways that spike and crash blood sugar, the mental gaps multiply.",
        "This is the fuel that closes the gap between what an athlete knows and what she can execute under pressure. A technically sound player who can't stay mentally sharp in the third quarter is leaving performance on the table. Focus fuel addresses that gap at the cellular level.",
      ],
      when: "Throughout the day, especially on competition days and high-stress practice days. Focus fuel is a daily habit, not a pre-game ritual.",
      lookFor: [
        "Omega-3 rich foods salmon, walnuts, flaxseed, chia seeds",
        "Antioxidant-rich foods blueberries, dark chocolate, leafy greens",
        "Slow-digesting carbs oats, quinoa, sweet potato",
        "Consistent hydration even mild dehydration reduces focus and decision-making",
      ],
      avoid: [
        "High-sugar foods that spike and crash blood sugar",
        "Skipping meals a brain that hasn't been fed cannot focus",
        "Excessive caffeine it spikes cortisol and increases anxiety",
        "Highly processed foods they create inflammation that affects brain function",
      ],
      lawTieIn: "The mental game is a physical game. You cannot think your way to focus when your body hasn't been fueled for it. Build the brain the same way you build the body consistently, over time.",
    },
    recipes: [
      r("focus", 1, {
        name: "Berry-Spinach Recovery Smoothie",
        why: "30g of protein plus antioxidants from berries, iron from spinach, calcium from yogurt, and omega-3s from walnuts and flaxseed. Drink within 45 minutes of training for best recovery.",
        prepTime: "3 min", cookTime: "0 min", servings: "1",
        protein: "30g", carbs: "35g", fat: "8g",
        pdfUrl: "berry-spinach-smoothie.pdf",
        ingredients: [
          "12 oz water",
          "1 cup spinach",
          "2 cups frozen mixed berries",
          "½ cup plain low-fat yogurt",
          "2 scoops vanilla protein powder",
          "1 tbsp walnuts",
          "1 tbsp ground flaxseed",
        ],
        instructions: [
          "Add all ingredients to a blender.",
          "Blend until smooth and creamy.",
          "Serve cold and drink within 45 minutes of training for best recovery.",
        ],
        athleteTip: "Best after intense practices or games and on strength-training days. Not ideal right before competition as high fiber may slow digestion.",
      }),
      r("focus", 2, {
        name: "Salmon Avocado Toast",
        why: "Omega-3s from salmon plus healthy fat from avocado make this one of the most powerful focus-support meals in the library. Both nutrients directly support brain cell function.",
        prepTime: "8 min", cookTime: "0 min", servings: "1",
        protein: "24g", carbs: "28g", fat: "18g",
        ingredients: [
          "2 slices whole grain bread, toasted",
          "3 oz smoked salmon or canned salmon",
          "½ ripe avocado",
          "1 tbsp lemon juice",
          "Salt, pepper, and red pepper flakes",
          "Optional: capers and fresh dill",
        ],
        instructions: [
          "Toast bread until golden.",
          "Mash avocado with lemon juice, salt, and pepper in a small bowl.",
          "Spread avocado mash evenly across both slices of toast.",
          "Layer salmon on top.",
          "Add capers, dill, and red pepper flakes to taste.",
        ],
        athleteTip: "Use leftover salmon from dinner the night before. Keep a ripe avocado on the counter always. Eat this as your morning meal on competition days for steady brain fuel.",
      }),
      r("focus", 3, {
        name: "Walnut & Dark Chocolate Trail Mix",
        why: "Walnuts are one of the most brain-supportive foods available. Their omega-3 content reduces cognitive inflammation and supports neural function. Dark chocolate improves blood flow to the brain.",
        prepTime: "5 min", cookTime: "0 min", servings: "4",
        protein: "8g", carbs: "22g", fat: "16g",
        ingredients: [
          "1 cup walnuts",
          "½ cup almonds",
          "¼ cup pumpkin seeds",
          "½ cup dark chocolate chips (70%+)",
          "¼ cup dried cherries or blueberries",
          "Optional: pinch of sea salt",
        ],
        instructions: [
          "Combine all ingredients in a large bowl.",
          "Mix well.",
          "Divide into 4 equal portions.",
          "Store in individual zip-lock bags or small containers.",
        ],
        athleteTip: "Make a big bag at the beginning of the week. Grab a handful before every practice and on competition days. Keep a portion in your backpack so focus fuel is always within reach.",
      }),
      r("focus", 4, {
        name: "Chia Seed Pudding",
        why: "Chia seeds deliver omega-3s, fiber, and slow-release energy. Made the night before for zero-effort focus fuel on competition morning. Steady energy with no blood sugar spike.",
        prepTime: "5 min", cookTime: "0 min", servings: "1",
        protein: "10g", carbs: "32g", fat: "12g",
        ingredients: [
          "¼ cup chia seeds",
          "1 cup milk or unsweetened almond milk",
          "1 tbsp honey or maple syrup",
          "½ tsp vanilla extract",
          "½ cup fresh berries for topping",
          "Optional: 1 tbsp nut butter swirled in",
        ],
        instructions: [
          "Mix chia seeds, milk, honey, and vanilla in a jar or bowl.",
          "Stir well to combine.",
          "Refrigerate minimum 2 hours or overnight.",
          "Stir again before serving — chia seeds should be fully absorbed.",
          "Top with fresh berries and nut butter if using.",
        ],
        athleteTip: "Make 5 jars on Sunday night. A week of focus fuel ready in the fridge. Stir after the first 10 minutes to prevent clumping at the bottom. Add toppings fresh each morning.",
      }),
      r("focus", 5, {
        name: "Avocado Egg Bites",
        why: "Eggs deliver choline, a nutrient critical for memory and focus that most athletes are deficient in. Avocado adds brain-healthy fat that supports sustained mental clarity.",
        prepTime: "10 min", cookTime: "25 min", servings: "3",
        protein: "14g", carbs: "6g", fat: "16g",
        ingredients: [
          "6 large eggs",
          "1 ripe avocado, diced",
          "¼ cup shredded cheese",
          "¼ cup diced bell pepper",
          "2 tbsp milk",
          "Salt, pepper, and garlic powder",
          "Optional: hot sauce",
        ],
        instructions: [
          "Preheat oven to 350°F. Grease a 6-cup muffin tin.",
          "Whisk eggs with milk, salt, pepper, and garlic powder.",
          "Fill each muffin cup halfway with the egg mixture.",
          "Add diced avocado, cheese, and bell pepper to each cup.",
          "Fill to the top with remaining egg mixture.",
          "Bake 20–25 minutes until set and lightly golden on top.",
        ],
        athleteTip: "Bake a full muffin tin of egg bites on Sunday. Grab 2 every morning. They reheat in 45 seconds. One of the easiest ways to start every day with real brain fuel.",
      }),
      r("focus", 6, {
        name: "Green Goddess Smoothie",
        why: "Spinach, banana, and almond butter deliver magnesium, potassium, and steady energy that supports focus for hours. Magnesium is critical for nerve function and most athletes are low in it.",
        prepTime: "5 min", cookTime: "0 min", servings: "1",
        protein: "12g", carbs: "34g", fat: "10g",
        ingredients: [
          "2 big handfuls baby spinach",
          "1 medium banana (frozen for creaminess)",
          "1 tbsp almond butter",
          "1 cup almond milk or milk",
          "½ cup plain Greek yogurt",
          "Optional: 1 tsp matcha powder or drizzle of honey",
        ],
        instructions: [
          "Add almond milk to blender first.",
          "Add spinach, frozen banana, almond butter, and Greek yogurt.",
          "Add matcha powder and honey if using.",
          "Blend until completely smooth. Add more liquid if too thick.",
          "Drink immediately.",
        ],
        athleteTip: "The key is real spinach, not spinach-flavored anything. Use 2 big handfuls. Freeze bananas in advance for a thicker, colder smoothie with a creamier texture.",
      }),
      r("focus", 7, {
        name: "Apple Walnut Slices with Cinnamon",
        why: "A simple snack that stabilizes blood sugar and delivers brain-healthy fats with zero prep time. Walnuts provide omega-3s and apples provide pectin fiber for steady glucose release.",
        prepTime: "5 min", cookTime: "0 min", servings: "1",
        protein: "5g", carbs: "28g", fat: "10g",
        ingredients: [
          "1 medium apple (any variety)",
          "2 tbsp walnuts, roughly chopped",
          "1 tbsp almond or peanut butter",
          "Sprinkle of cinnamon",
          "Optional: drizzle of honey",
        ],
        instructions: [
          "Core and slice the apple.",
          "Arrange slices on a plate or in a container.",
          "Sprinkle chopped walnuts over the apple slices.",
          "Drizzle nut butter across the top.",
          "Dust with cinnamon and honey if using.",
        ],
        athleteTip: "Keep walnuts and apples in your backpack. This snack requires no refrigeration for up to 4 hours and is ready anywhere, anytime. One of the best between-class or pre-practice focus snacks.",
      }),
      r("focus", 8, {
        name: "Mixed Berry Greek Yogurt",
        why: "Greek yogurt plus antioxidant-rich berries plus omega-3-rich walnuts in one bowl. The combination of protein, healthy fat, and slow carbs delivers sustained mental energy.",
        prepTime: "5 min", cookTime: "0 min", servings: "1",
        protein: "18g", carbs: "30g", fat: "8g",
        ingredients: [
          "1 cup plain Greek yogurt (full fat)",
          "1 cup mixed berries (fresh or thawed frozen)",
          "2 tbsp walnuts",
          "1 tbsp honey",
          "Optional: chia seeds or hemp seeds",
        ],
        instructions: [
          "Scoop Greek yogurt into a bowl.",
          "Top with mixed berries.",
          "Add walnuts.",
          "Drizzle honey over the top.",
          "Sprinkle chia or hemp seeds if using.",
        ],
        athleteTip: "Add walnuts right before eating to keep them crunchy. Use local honey if you can find it. Works as breakfast, a mid-day snack, or light recovery fuel after a short session.",
      }),
      r("focus", 9, {
        name: "Dark Chocolate Almond Bark",
        why: "Dark chocolate (70%+) improves blood flow to the brain and supports focus. Almonds add magnesium and healthy fat. A small amount goes a long way.",
        prepTime: "10 min", cookTime: "5 min", servings: "8",
        protein: "5g", carbs: "14g", fat: "12g",
        ingredients: [
          "1½ cups dark chocolate chips (70%+)",
          "½ cup roasted almonds, roughly chopped",
          "¼ cup dried blueberries or cranberries",
          "2 tbsp pumpkin seeds",
          "Pinch of sea salt",
        ],
        instructions: [
          "Melt chocolate chips in a microwave-safe bowl in 30-second bursts, stirring between each until smooth.",
          "Spread melted chocolate in an even layer on a parchment-lined baking sheet.",
          "Sprinkle almonds, dried berries, pumpkin seeds, and sea salt evenly over the top.",
          "Refrigerate 20–30 minutes until fully set.",
          "Break into pieces and store in an airtight container.",
        ],
        athleteTip: "Make a batch, break it into pieces, and keep it in an airtight container. Lasts 2 weeks in the fridge. Grab one or two pieces as a focus snack between classes or before an evening practice.",
      }),
      r("focus", 10, {
        name: "Rainbow Veggie Hummus Plate",
        why: "Hydrating vegetables with hummus delivers fiber, protein, and healthy fat for steady energy without a spike. The variety of colors means a variety of antioxidants for brain protection.",
        prepTime: "10 min", cookTime: "0 min", servings: "2",
        protein: "10g", carbs: "28g", fat: "10g",
        ingredients: [
          "½ cup hummus",
          "1 cup baby carrots",
          "1 cup celery sticks",
          "1 bell pepper, sliced into strips",
          "1 cup cucumber slices",
          "10 whole grain crackers",
          "Optional: cherry tomatoes and snap peas",
        ],
        instructions: [
          "Scoop hummus into the center of a plate or container.",
          "Arrange carrots, celery, bell pepper, and cucumber around the hummus.",
          "Add crackers on the side.",
          "Add cherry tomatoes and snap peas if using.",
        ],
        athleteTip: "Prep all the vegetables on Sunday. Cut everything, store in containers, and keep hummus portioned in small cups. A full plate ready to grab from the fridge all week — zero decisions required.",
      }),
    ],
  },
  {
    id: "build",
    label: "Build Fuel",
    accentColor: "#982FF7",
    tagline: "What supports muscle development and physical growth.",
    overview: {
      paragraphs: [
        "Building an athlete's body is a long-term project not something that happens in one meal or one week. The decisions made today show up in the body 6 weeks from now. Build fuel is about consistency over intensity.",
        "Build fuel is consistent high-quality protein throughout the day, enough total calories to support growth and training load, and micronutrients that support bone density and hormonal health. Under-fueling is the most common mistake young female athletes make, and it is the one with the longest-term consequences.",
        "The goal is 0.7–1g of protein per pound of body weight per day, spread across 3–5 meals. Not all in one shake. Protein synthesis the process of actually building muscle requires a steady supply throughout the day. Front-loading all your protein in one meal defeats the purpose.",
      ],
      when: "Throughout the day in 3–5 evenly spaced meals. Prioritize protein with every meal. Don't wait until dinner to hit your protein target.",
      lookFor: [
        "Complete proteins with all essential amino acids meat, eggs, dairy, soy",
        "Total daily protein: roughly 0.7–1g per pound of body weight",
        "Enough total calories you cannot build muscle in a caloric deficit",
        "Calcium and Vitamin D for bone density especially critical for female athletes",
      ],
      avoid: [
        "Chronic under-eating the most common mistake in female youth athletics",
        "Skipping meals during high training volume periods",
        "Relying on one large protein source per day instead of spreading intake",
        "Restricting carbohydrates carbs spare protein for muscle building instead of energy",
      ],
      lawTieIn: "Building the body is a daily commitment, not a weekly event. Consistency is the only variable that compounds. Show up to every meal the way you show up to every practice.",
    },
    recipes: [
      r("build", 1, {
        name: "Buffalo Chicken Dip",
        why: "32g of protein per serving with zero cooking required. Shredded chicken and whipped cottage cheese deliver complete amino acids in a format that works as a snack, post-practice fuel, or tournament day staple.",
        prepTime: "10 min", cookTime: "0 min", servings: "6",
        protein: "32g", carbs: "3g", fat: "7g",
        pdfUrl: "buffalo-chicken-dip.pdf",
        ingredients: [
          "3 cups cooked, shredded chicken breast",
          "1½ cups whipped cheese (blend cottage cheese until smooth and creamy)",
          "¼–½ cup buffalo sauce (adjust for spice tolerance)",
          "¼ cup plain Greek yogurt (optional, for extra creaminess)",
          "Optional: chopped green onions, garlic powder, or onion powder",
          "Dippers: carrot sticks, celery sticks, whole wheat or seeded crackers (2–3g fiber per serving)",
        ],
        instructions: [
          "Add cottage cheese to a blender and blend until completely smooth. This is your whipped cheese.",
          "In a large bowl, mix whipped cheese, buffalo sauce, and Greek yogurt if using.",
          "Fold in shredded chicken until evenly coated.",
          "Chill or serve immediately. No baking required.",
        ],
        athleteTip: "Best after practice or games and as a high-protein afternoon snack. Avoid right before intense activity as spice and dairy may upset some stomachs.",
      }),
      r("build", 2, {
        name: "Ground Beef & Veggie Stir Fry",
        why: "Ground beef delivers complete protein plus zinc and iron, two minerals female athletes commonly run low on. Zinc supports recovery and iron carries oxygen to working muscles.",
        prepTime: "10 min", cookTime: "15 min", servings: "2",
        protein: "38g", carbs: "22g", fat: "16g",
        ingredients: [
          "1 lb lean ground beef (90/10)",
          "2 cups broccoli florets",
          "1 cup sliced bell peppers",
          "1 cup snap peas",
          "2 cloves garlic, minced",
          "1 tbsp soy sauce",
          "1 tbsp oyster sauce or hoisin sauce",
          "1 tsp sesame oil",
          "1 tbsp avocado oil",
          "Salt and pepper to taste",
        ],
        instructions: [
          "Heat avocado oil in a large pan or wok over high heat.",
          "Add ground beef and break apart with a spoon. Cook until no longer pink, about 5–6 minutes. Drain excess fat.",
          "Add garlic and cook 1 minute.",
          "Add broccoli, bell peppers, and snap peas. Stir-fry 4–5 minutes until tender-crisp.",
          "Add soy sauce, oyster sauce, and sesame oil. Toss to coat everything evenly.",
          "Serve immediately over white rice or eat straight from the pan.",
        ],
        athleteTip: "Add 2 eggs to the last minute of cooking for extra protein and richness. Serve over white rice on heavy training days when you need more carbs. Prep doubles easily.",
      }),
      r("build", 3, {
        name: "Triple-Source Protein Bowl",
        why: "Layering Greek yogurt, cottage cheese, and protein powder creates a 50g+ protein meal that doesn't feel like a supplement. Three protein sources means a full amino acid profile.",
        prepTime: "5 min", cookTime: "0 min", servings: "1",
        protein: "52g", carbs: "24g", fat: "12g",
        ingredients: [
          "¾ cup plain Greek yogurt (full fat)",
          "½ cup low-fat cottage cheese",
          "1 scoop vanilla protein powder",
          "¼ cup blueberries or sliced strawberries",
          "1 tbsp honey",
          "2 tbsp granola",
          "Optional: 1 tsp chia seeds",
        ],
        instructions: [
          "Blend or stir cottage cheese until smooth.",
          "Combine with Greek yogurt in a bowl. Mix well.",
          "Stir in protein powder until fully combined and no clumps remain.",
          "Spoon into a bowl.",
          "Top with fruit, granola, honey, and chia seeds.",
        ],
        athleteTip: "Use full-fat Greek yogurt and full-fat cottage cheese. Dietary fat is not the enemy in a build phase. This hits 50g+ protein without feeling like you're eating a supplement.",
      }),
      r("build", 4, {
        name: "Egg White Power Scramble",
        why: "Egg whites are pure protein with almost zero fat. Pairing with a whole egg adds essential fat-soluble vitamins and choline critical for brain and muscle function.",
        prepTime: "5 min", cookTime: "8 min", servings: "1",
        protein: "28g", carbs: "8g", fat: "8g",
        ingredients: [
          "¾ cup liquid egg whites (about 6 egg whites)",
          "1 whole egg",
          "1 cup baby spinach",
          "¼ cup diced tomato",
          "1 tbsp olive oil or butter",
          "Salt, pepper, and garlic powder",
          "Optional: shredded cheese or salsa",
        ],
        instructions: [
          "Whisk egg whites and whole egg together in a bowl.",
          "Season with salt, pepper, and garlic powder.",
          "Heat oil in a non-stick pan over medium heat.",
          "Pour in egg mixture. Add spinach and tomato.",
          "Stir gently and continuously until eggs are just set, about 3–4 minutes.",
          "Top with cheese or salsa if using.",
        ],
        athleteTip: "The 4-egg-white to 1-whole-egg ratio is the standard. Don't skip the whole egg. The yolk has choline critical for muscle repair and brain function. Skip it and you're leaving nutrients on the table.",
      }),
      r("build", 5, {
        name: "Protein Pancake Stack",
        why: "A high-protein breakfast that makes hitting your daily protein target easier without eating chicken at 7am. Oat flour provides steady carbs and Greek yogurt adds extra protein.",
        prepTime: "5 min", cookTime: "10 min", servings: "2",
        protein: "32g", carbs: "38g", fat: "8g",
        ingredients: [
          "1 cup rolled oats (blended into flour)",
          "2 scoops vanilla protein powder",
          "2 large eggs",
          "½ cup plain Greek yogurt",
          "½ cup milk",
          "1 tsp baking powder",
          "1 tsp vanilla extract",
          "Pinch of salt",
          "Optional: fresh berries and maple syrup to serve",
        ],
        instructions: [
          "Blend rolled oats in a blender until a fine flour forms.",
          "Mix oat flour, protein powder, baking powder, and salt in a bowl.",
          "Whisk eggs, Greek yogurt, milk, and vanilla in a separate bowl.",
          "Combine wet and dry ingredients. Stir until just mixed — small lumps are fine.",
          "Cook on a lightly greased pan over medium heat, 2–3 minutes per side.",
          "Serve topped with fresh berries and a drizzle of maple syrup.",
        ],
        athleteTip: "Freeze extra pancakes flat on a baking sheet then bag them. Toast from frozen in 2 minutes. Game-morning or post-practice protein sorted with zero effort.",
      }),
      r("build", 6, {
        name: "Turkey Meatball Meal Prep",
        why: "Turkey meatballs are a lean, versatile protein source with less saturated fat than beef. Batch-prep and use them across multiple meals throughout the week.",
        prepTime: "15 min", cookTime: "20 min", servings: "4",
        protein: "36g", carbs: "14g", fat: "12g",
        ingredients: [
          "1½ lbs lean ground turkey",
          "¼ cup breadcrumbs",
          "1 egg",
          "2 cloves garlic, minced",
          "1 tbsp fresh parsley or 1 tsp dried",
          "1 tsp Italian seasoning",
          "½ tsp salt",
          "¼ tsp pepper",
          "Optional: marinara sauce for serving",
        ],
        instructions: [
          "Preheat oven to 400°F. Line a baking sheet with parchment paper.",
          "Mix all ingredients together in a large bowl until just combined.",
          "Use an ice cream scoop to portion meatballs evenly.",
          "Roll into balls and place on the baking sheet about 1 inch apart.",
          "Bake 18–20 minutes until cooked through (internal temp 165°F).",
          "Serve with marinara, over pasta, or with rice and vegetables.",
        ],
        athleteTip: "Use an ice cream scoop to portion meatballs evenly — consistent size means they all cook at the same rate. Bake at 400°F, no flipping needed. Make a double batch and freeze half.",
      }),
      r("build", 7, {
        name: "Lentil & Chicken Soup",
        why: "Lentils deliver plant-based protein plus iron, folate, and slow carbs. Combined with chicken this becomes a complete build meal with over 30g protein and anti-inflammatory benefits.",
        prepTime: "10 min", cookTime: "35 min", servings: "6",
        protein: "32g", carbs: "38g", fat: "6g",
        ingredients: [
          "1 lb chicken breast",
          "1½ cups red or green lentils, rinsed",
          "1 can (14 oz) diced tomatoes",
          "4 cups low-sodium chicken broth",
          "1 onion, diced",
          "2 carrots, sliced",
          "3 cloves garlic, minced",
          "1 tsp cumin",
          "1 tsp turmeric",
          "1 tbsp olive oil",
          "Salt and pepper to taste",
          "Fresh parsley to garnish",
        ],
        instructions: [
          "Heat olive oil in a large pot over medium heat. Sauté onion and carrots 4–5 minutes.",
          "Add garlic, cumin, and turmeric. Cook 1 minute until fragrant.",
          "Add whole chicken breasts, rinsed lentils, diced tomatoes, and broth.",
          "Bring to a boil then reduce heat. Simmer 25–30 minutes until chicken is cooked through.",
          "Remove chicken, shred with two forks, and return to the pot.",
          "Season with salt and pepper. Garnish with fresh parsley.",
        ],
        athleteTip: "Make a big pot on Sunday. This freezes perfectly and reheats in 3 minutes from the microwave. Stays fresh in the fridge for 5 days. One of the best value build meals in the library.",
      }),
      r("build", 8, {
        name: "Tuna Power Salad",
        why: "Canned tuna is one of the highest protein-to-cost foods available. Two cans deliver 36g of complete protein plus omega-3s for recovery. A full build meal in 10 minutes.",
        prepTime: "10 min", cookTime: "0 min", servings: "2",
        protein: "36g", carbs: "18g", fat: "12g",
        ingredients: [
          "2 cans (5 oz each) tuna in water, drained",
          "4 cups mixed greens",
          "1 cup cherry tomatoes, halved",
          "½ cup cucumber, sliced",
          "¼ red onion, thinly sliced",
          "2 tbsp olive oil",
          "1 tbsp lemon juice",
          "1 tsp Dijon mustard",
          "Salt and pepper to taste",
        ],
        instructions: [
          "Drain tuna completely and fluff with a fork.",
          "Combine mixed greens, cherry tomatoes, cucumber, and red onion in a large bowl.",
          "Whisk together olive oil, lemon juice, Dijon mustard, salt, and pepper to make the dressing.",
          "Add tuna to the salad.",
          "Drizzle dressing and toss gently to combine.",
        ],
        athleteTip: "Use olive oil and lemon dressing. Healthy fat helps absorb the fat-soluble vitamins in the greens. Keep canned tuna stocked always. It's the highest protein-to-cost ratio in the entire library.",
      }),
      r("build", 9, {
        name: "Cottage Cheese Protein Bowl",
        why: "Cottage cheese is high in casein, a slow-digesting protein that continues amino acid delivery for hours after eating. Best consumed before bed or between meals during high-volume training.",
        prepTime: "5 min", cookTime: "0 min", servings: "1",
        protein: "30g", carbs: "20g", fat: "8g",
        ingredients: [
          "1½ cups full-fat cottage cheese",
          "1 scoop vanilla protein powder",
          "1 tbsp natural almond or peanut butter",
          "½ banana, sliced",
          "1 tbsp honey",
          "Optional: sprinkle of cinnamon",
        ],
        instructions: [
          "Scoop cottage cheese into a bowl.",
          "Stir in protein powder until fully combined and smooth.",
          "Add nut butter and fold gently.",
          "Top with banana slices.",
          "Drizzle honey and dust with cinnamon if using.",
        ],
        athleteTip: "Add a tablespoon of nut butter and a scoop of protein powder to amplify protein content and calories. This bowl before bed on heavy training days gives your muscles amino acids to work with overnight.",
      }),
      r("build", 10, {
        name: "Baked Chicken & Quinoa",
        why: "The simplest high-protein meal prep recipe in the library. Chicken provides complete protein and quinoa is the only grain that delivers all essential amino acids. Four ingredients, one pan.",
        prepTime: "10 min", cookTime: "30 min", servings: "4",
        protein: "42g", carbs: "32g", fat: "8g",
        ingredients: [
          "4 chicken breasts (about 6 oz each)",
          "1 cup quinoa (dry)",
          "2 cups low-sodium chicken broth",
          "2 tbsp olive oil",
          "1 tsp garlic powder",
          "1 tsp paprika",
          "1 tsp Italian seasoning",
          "Salt and pepper to taste",
          "Optional: lemon zest and fresh parsley",
        ],
        instructions: [
          "Preheat oven to 400°F.",
          "Cook quinoa in chicken broth over medium heat 12–15 minutes until fluffy. Fluff with a fork.",
          "Drizzle chicken breasts with olive oil and season with garlic powder, paprika, Italian seasoning, salt, and pepper.",
          "Bake on a lined baking sheet 22–25 minutes until internal temp reaches 165°F.",
          "Rest chicken 5 minutes then slice.",
          "Serve chicken over quinoa. Top with parsley and lemon zest if using.",
        ],
        athleteTip: "Use chicken thighs instead of breast for more calories and flavor during high-training-volume weeks. Prep 4 portions and you have lunch and dinner handled for 2 days straight.",
      }),
    ],
  },
  {
    id: "quick",
    label: "Quick Fuel",
    accentColor: "#C42BEE",
    tagline: "Fast, practical options for busy athlete schedules.",
    overview: {
      paragraphs: [
        "Athlete schedules are brutal early morning practice, school, afternoon training, tournaments that run all day. Quick fuel is not a compromise. It is a system that keeps the athlete fueled when the clock is working against her.",
        "Quick fuel is not junk food it is smart, portable, practical nutrition that works when there is no time to cook. The goal is options that travel well, require no or minimal prep, and still deliver real fuel: protein, carbs, or healthy fat depending on the timing.",
        "The key is preparation, not willpower. An athlete who has a quick fuel kit ready a bag of trail mix, some rice cakes, hard-boiled eggs prepped on Sunday never has to choose between bad options. Build the system once. Use it all week.",
      ],
      when: "Between meals, during tournaments, on travel days, or any time a full meal isn't possible and training or competition is within 2 hours.",
      lookFor: [
        "Single-ingredient or minimal-ingredient foods",
        "Options that don't require refrigeration for travel",
        "Foods that deliver protein, carbs, or healthy fat not just calories",
        "Things that can be batch-prepped on Sunday for the whole week",
      ],
      avoid: [
        "Vending machine defaults chips, cookies, candy they create energy crashes",
        "Going longer than 4 hours without eating anything on training or competition days",
        "Relying on sports drinks as a meal replacement they are hydration tools, not fuel",
        "Waiting until you're starving to figure out what to eat",
      ],
      lawTieIn: "Preparation is the performance skill no one talks about. An athlete who has her quick fuel ready is already ahead of the one who shows up hoping for the best.",
    },
    recipes: [
      r("quick", 1, {
        name: "Acai Bowl",
        why: "Natural sugars and carbohydrates from frozen acai and fruit give a clean energy base without heaviness. No baking, no cooking, ready in 5 minutes.",
        prepTime: "5 min", cookTime: "0 min", servings: "2",
        protein: "5g", carbs: "45g", fat: "6g",
        pdfUrl: "acai-bowl.pdf",
        ingredients: [
          "2 frozen acai packets",
          "1 cup frozen berries (strawberries, blueberries, raspberries) or mango/pineapple",
          "½–¾ cup liquid (water, milk alternative, or fruit juice)",
          "Toppings: granola (about ½ cup per bowl)",
          "Toppings: coconut flakes",
          "Toppings: fresh fruit (banana, strawberries, kiwi, blueberries)",
          "Toppings: drizzle of nut butter (1–2 tbsp)",
          "Toppings: honey or agave (1 tsp–1 tbsp)",
          "Toppings: chia seeds",
        ],
        instructions: [
          "Blend acai packets, frozen fruit, and liquid until thick and creamy. Start with less liquid and add as needed.",
          "Scoop into bowls.",
          "Add toppings in colorful rows or fun patterns.",
        ],
        athleteTip: "Keep toppings bite-sized for easier eating. Not right before intense activity as the liquid base and fruit sugars can cause GI discomfort mid-competition if eaten too close to game time.",
      }),
      r("quick", 2, {
        name: "PB & Banana Rice Cakes",
        why: "The most portable 2-minute snack in the library. Delivers steady carbs from rice cakes, natural sugar from banana, and a little protein and fat from peanut butter.",
        prepTime: "3 min", cookTime: "0 min", servings: "1",
        protein: "7g", carbs: "40g", fat: "8g",
        ingredients: [
          "3 plain rice cakes",
          "2 tbsp natural peanut butter",
          "1 small banana, sliced",
          "Optional: drizzle of honey",
        ],
        instructions: [
          "Lay rice cakes on a plate or flat surface.",
          "Spread peanut butter evenly on each rice cake.",
          "Layer banana slices on top.",
          "Drizzle honey if using.",
          "Eat immediately.",
        ],
        athleteTip: "Keep a bag of rice cakes and a jar of PB at school or in your tournament bag permanently. This snack is never more than 3 minutes away and requires zero refrigeration.",
      }),
      r("quick", 3, {
        name: "Power Trail Mix",
        why: "A customizable mix that travels anywhere, lasts for weeks, and delivers real fuel in minutes. Walnuts, almonds, and seeds provide protein, healthy fat, and brain-supportive omega-3s.",
        prepTime: "5 min", cookTime: "0 min", servings: "4",
        protein: "8g", carbs: "22g", fat: "14g",
        ingredients: [
          "1 cup walnuts",
          "1 cup almonds",
          "½ cup pumpkin seeds",
          "½ cup dark chocolate chips (70%+)",
          "½ cup dried cherries or cranberries",
          "Optional: ¼ cup unsweetened coconut flakes",
        ],
        instructions: [
          "Combine all ingredients in a large bowl.",
          "Mix well.",
          "Divide into 4 equal portions.",
          "Store each portion in a zip-lock bag or small container.",
        ],
        athleteTip: "Make a big batch at the start of the week. Keep a portion in your backpack, gym bag, and car. This is your backup fuel when nothing else is available. No refrigeration needed.",
      }),
      r("quick", 4, {
        name: "Prep & Freeze Smoothie Pouches",
        why: "Pre-blend, freeze flat in bags, and blend or thaw on the go. Tournament smoothies without the chaos. A full protein and carb hit in under 2 minutes when you have a blender.",
        prepTime: "20 min", cookTime: "0 min", servings: "5",
        protein: "20g", carbs: "38g", fat: "5g",
        ingredients: [
          "Per pouch: 1 cup frozen mixed berries",
          "Per pouch: 1 large handful baby spinach",
          "Per pouch: 1 medium banana (sliced and pre-frozen)",
          "Per pouch: 1 scoop vanilla protein powder",
          "To blend: 1 cup milk or water per pouch (added fresh when blending)",
        ],
        instructions: [
          "Portion frozen berries, spinach, banana slices, and protein powder into 5 individual zip-lock bags.",
          "Seal bags and freeze flat so they stack easily.",
          "To use: dump one bag into a blender, add 1 cup of liquid, and blend until smooth.",
          "Drink within 20 minutes.",
        ],
        athleteTip: "Freeze flat so bags stack in the freezer. On tournament days, pack a frozen pouch in a cooler bag — it thaws slowly and can be blended at the hotel or venue. 5 bags Sunday equals 5 smoothies all week.",
      }),
      r("quick", 5, {
        name: "Hard-Boiled Egg Pack",
        why: "The simplest high-protein portable snack that exists. Eggs provide complete protein with all essential amino acids, zero added ingredients, and zero prep on game day.",
        prepTime: "5 min", cookTime: "12 min", servings: "1",
        protein: "18g", carbs: "2g", fat: "12g",
        ingredients: [
          "3 large eggs",
          "Pinch of salt",
          "Optional: hot sauce or everything bagel seasoning",
        ],
        instructions: [
          "Place eggs in a saucepan. Cover with cold water by 1 inch.",
          "Bring to a full boil over high heat.",
          "Remove from heat, cover with a lid, and let sit 10–12 minutes.",
          "Transfer eggs to an ice bath for 5 minutes to stop cooking.",
          "Peel immediately or store unpeeled in the fridge for up to 1 week.",
        ],
        athleteTip: "Hard-boil a full dozen eggs on Sunday. Pack 2–3 in a small container with a pinch of salt and some hot sauce. Zero additives, zero prep on game day, and the easiest protein source you will ever carry.",
      }),
      r("quick", 6, {
        name: "Grab-and-Go Overnight Oats",
        why: "Made the night before in a mason jar. Grab it from the fridge and eat on the drive. Rolled oats provide slow-release carbs that fuel a long morning without a crash.",
        prepTime: "5 min", cookTime: "0 min", servings: "1",
        protein: "14g", carbs: "52g", fat: "7g",
        ingredients: [
          "½ cup rolled oats (not instant)",
          "¾ cup almond milk or regular milk",
          "¼ cup plain Greek yogurt",
          "1 tbsp chia seeds",
          "1 tbsp honey",
          "½ cup fresh or frozen berries",
        ],
        instructions: [
          "Combine oats, almond milk, Greek yogurt, chia seeds, and honey in a mason jar.",
          "Stir well.",
          "Top with berries.",
          "Seal the jar and refrigerate overnight.",
          "Grab cold from the fridge in the morning and eat as-is.",
        ],
        athleteTip: "The trick is rolled oats, not instant oats. Regular oats in almond milk overnight deliver real sustained energy that instant oats don't match. Make 5 jars Sunday and the whole week is handled.",
      }),
      r("quick", 7, {
        name: "Jerky & Fruit Pack",
        why: "High protein from jerky, fast carbs from fruit, and healthy fat from almonds. A complete quick fuel combo that requires zero refrigeration and travels to any venue.",
        prepTime: "5 min", cookTime: "0 min", servings: "1",
        protein: "16g", carbs: "30g", fat: "6g",
        ingredients: [
          "1½ oz beef or turkey jerky (low sodium)",
          "1 medium apple",
          "1 oz almonds (small handful)",
          "Optional: 1 stick string cheese for extra protein",
        ],
        instructions: [
          "Pack jerky, apple, and almonds in a zip-lock bag or small divided container.",
          "Add string cheese if using.",
          "Done — ready to grab.",
        ],
        athleteTip: "Use high-quality jerky with low sodium. Check the label — some jerky brands have more sugar than protein. This pack requires no refrigeration for several hours and is one of the most reliable tournament day snacks.",
      }),
      r("quick", 8, {
        name: "String Cheese & Apple Slices",
        why: "Four ingredients, zero cooking, ready in 2 minutes. One of the most consistently useful athlete snacks in the library. Protein from cheese, carbs and fiber from apple.",
        prepTime: "3 min", cookTime: "0 min", servings: "1",
        protein: "8g", carbs: "22g", fat: "5g",
        ingredients: [
          "2 sticks string cheese",
          "1 medium apple (any variety)",
          "Optional: 1 tbsp almond butter for dipping",
        ],
        instructions: [
          "Slice the apple into wedges or leave whole.",
          "Pair with 2 string cheese sticks.",
          "Add almond butter on the side if using.",
        ],
        athleteTip: "Keep string cheese and apples in the fridge at all times. This snack is never more than 2 minutes away. One of the most reliable, no-excuse athlete snacks that works at any time of day.",
      }),
      r("quick", 9, {
        name: "Tournament Day Snack Box",
        why: "A full snack strategy for a long tournament day planned in advance so decisions are already made. Eliminates vending machine emergencies and energy crashes between games.",
        prepTime: "10 min", cookTime: "0 min", servings: "1",
        protein: "24g", carbs: "52g", fat: "14g",
        ingredients: [
          "2 hard-boiled eggs",
          "1 stick string cheese",
          "1 banana",
          "1 oz almonds",
          "1 cup grapes",
          "2 rice cakes with peanut butter",
          "1 small bag of pretzels",
          "Optional: 1 protein bar as emergency backup",
        ],
        instructions: [
          "Pack everything into a divided container or individual zip-lock bags the night before.",
          "Lay out all components and arrange so each snack is easy to grab between games.",
          "Place the box in your bag that night so the morning is completely automatic.",
        ],
        athleteTip: "Pack the box the night before a tournament. Lay out everything so morning is automatic. Plan one savory option, one sweet option, and a real protein source for every 2–3 hours you'll be competing.",
      }),
      r("quick", 10, {
        name: "No-Bake Energy Date Balls",
        why: "No baking required. Medjool dates, oats, and peanut butter deliver carbs, healthy fat, and a small amount of protein. Make 20 in 20 minutes and you have snacks for the whole week.",
        prepTime: "20 min", cookTime: "0 min", servings: "5",
        protein: "6g", carbs: "32g", fat: "8g",
        ingredients: [
          "1 cup Medjool dates, pitted",
          "½ cup rolled oats",
          "¼ cup natural peanut butter",
          "2 tbsp honey",
          "¼ cup dark chocolate chips",
          "Optional: shredded coconut for rolling",
        ],
        instructions: [
          "Pulse dates in a food processor until a thick paste forms.",
          "Add oats, peanut butter, honey, and chocolate chips. Pulse until combined.",
          "Transfer to a bowl and refrigerate 30 minutes.",
          "Roll into 1-inch balls using your hands.",
          "Roll in shredded coconut if using. Store refrigerated up to 2 weeks.",
        ],
        athleteTip: "Use Medjool dates, they're softer and sweeter than regular dates. Roll in shredded coconut to keep them from sticking together. Make 20 on Sunday and you're set for the entire week.",
      }),
    ],
  },
];

export const FUEL_CATEGORY_MAP: Record<FuelCategoryId, FuelCategory> = Object.fromEntries(
  FUEL_CATEGORIES.map(c => [c.id, c])
) as Record<FuelCategoryId, FuelCategory>;
